name: CD Pipeline (Deploy to AWS EC2)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Executar Deploy via SSH no EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/f1-race-intelligence
            docker compose down
            docker system prune -af --volumes
            docker builder prune -af 
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build